---
- name: Simple LAMP Setup with PHP Server on Port 80
  hosts: webservers
  become: true
  
  tasks:
    - name: Update packages
      apt:
        update_cache: true
        
    - name: Install LAMP stack
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - mysql-client
          - python3
          - python3-pip
          - certbot
          - python3-certbot-apache
          - git
        state: present
        
    - name: Create /root/api directory
      file:
        path: /root/api
        state: directory
        mode: '0755'
        
    - name: Clone PHP app from GitHub
      git:
        repo: "https://github.com/Kevinkimanzi/simple_php.git"
        dest: "/root/api"
        clone: true
        force: true
        
    - name: Set permissions for PHP files
      file:
        path: /root/api
        owner: root
        group: root
        mode: '0755'
        recurse: true

    # Stop Apache to free up port 80
    - name: Stop and disable Apache
      systemd:
        name: apache2
        state: stopped
        enabled: false
        
    - name: Stop any existing PHP server
      shell: pkill -f "php -S" || true
      ignore_errors: true
      
    - name: Create PHP server systemd service on port 80
      copy:
        content: |
          [Unit]
          Description=PHP Built-in Server on Port 80
          After=network.target
          
          [Service]
          Type=simple
          User=root
          WorkingDirectory=/root/api
          ExecStart=/usr/bin/php -S 0.0.0.0:80
          Restart=always
          RestartSec=3
          
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/php-server.service
        mode: '0644'
      notify: 
        - reload systemd
        - restart php-server
        
    - name: Start and enable PHP server service
      systemd:
        name: php-server
        state: started
        enabled: true
        daemon_reload: true

  handlers:        
    - name: reload systemd
      systemd:
        daemon_reload: true
        
    - name: restart php-server
      systemd:
        name: php-server
        state: restarted