---
- name: Simple LAMP Setup
  hosts: webservers
  become: true
  
  tasks:
    - name: Update packages
      apt:
        update_cache: true
        
    - name: Install LAMP stack
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - mysql-client
          - python3
          - python3-pip
          - certbot
          - python3-certbot-apache
        state: present
        
    - name: Create /root/api directory
      file:
        path: /root/api
        state: directory
        mode: '0755'
        
    - name: Configure Apache with SSL ready
      template:
        src: templates/apache.conf.j2
        dest: /etc/apache2/sites-available/default.conf
      notify: restart apache
        
    - name: Enable default site
      command: a2ensite default.conf
      notify: restart apache
      
    - name: Disable default Apache site
      command: a2dissite 000-default
      ignore_errors: true
      notify: restart apache

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted
        enabled: true